heat_template_version: 2015-10-15

description: Enroll nodes to FreeIPA

parameters:
  # Parameters passed from the parent template
  controller_servers:
    type: json
  compute_servers:
    type: json
  blockstorage_servers:
    type: json
  objectstorage_servers:
    type: json
  cephstorage_servers:
    type: json

  FreeIPAOTP:
    description: 'OTP that will be used for FreeIPA enrollment'
    type: string
    default: ThisIsMySecret
    hidden: true
  FreeIPAServer:
    description: 'FreeIPA server DNS name'
    type: string
  FreeIPADomain:
    description: 'FreeIPA domain; this will also be used as the kerberos realm'
    type: string

resources:
  FreeIPAEnrollmentConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: script
      inputs:
        - name: otp
        - name: ipa_server
        - name: ipa_domain
      config:
        #!/bin/sh
        yum install -y ipa-client
        if [ ! -f /etc/krb5.keytab ]; then
            ipa-client-install --server ${ipa_server} -w ${otp} \
                --domain=${ipa_domain} -U
        fi
        kinit -k -t /etc/krb5.keytab

  FreeIPAEnrollmentDeployment:
    type: OS::Heat::StructuredDeploymentGroup
    properties:
      name: FreeIPAEnrollmentDeployment
      config: {get_resource: FreeIPAEnrollmentConfig}
      servers: {get_param: controller_servers}
      input_values:
        otp: {get_param: FreeIPAOTP}
        ipa_server: {get_param: FreeIPAServer}
        ipa_domain: {get_param: FreeIPADomain}

outputs:
  deploy_stdout:
    description: Output of the FreeIPA enrollment deployment
    value: {get_attr: [FreeIPAEnrollmentDeployment, deploy_stdout]}
